export type ErrorCode =
  | "BAD_REQUEST"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "CONFLICT"
  | "NOT_FOUND"
  | "VALIDATION_FAILED"
  | "RATE_LIMITED"
  | "UNSUPPORTED_GAME_TYPE"
  | "SCOREBOOK_VALIDATION_FAILED"
  | "PERSISTENCE_ERROR"
  | "INTERNAL_ERROR";
